library(DESeq2)
library(RSkittleBrewer)
library(genefilter)
library(dplyr)
library(devtools)
rm(list=ls(all=TRUE)) 

add_bias_fromFC <- function(sbg_df, cts, pheno_data){
  # pick a gene with highest l2fc and determine sex-bias
  # from that
  gene <- as.character(sbg_df$gene_id[order(sbg_df$l2fc, decreasing = TRUE)][1])
  l2fc_gene <- sbg_df$l2fc[sbg_df$gene_id == gene]
  # get expression of gene in males and females.
  male_exp <- rowMeans(cts[gene, pheno_data$Ids[pheno_data$Sex == 'm']])
  female_exp <- rowMeans(cts[gene, pheno_data$Ids[pheno_data$Sex == 'f']])
  # sex-biased data frame that contains sex-bias
  sbg_df_out <- sbg_df
  sbg_df_out$sex <- sbg_df$l2fc
  
  if(male_exp>female_exp){
    sbg_df_out[sbg_df_out$sex >0,'sex'] <- 'm'
    sbg_df_out[sbg_df_out$sex <0,'sex'] <- 'f'
  }else{
    sbg_df_out[sbg_df_out$sex >0,'sex'] <- 'f'
    sbg_df_out[sbg_df_out$sex <0,'sex'] <- 'm'
    }
  
  return(sbg_df_out)
}

#######_______________Get sex-biased genes using DESeq2
run_DESeq <- function(species, signif, counts_mat, exp_folder){
  
  # counts matrix generated by prepDE.py
  cts <- read.csv(paste0(species,'/',counts_mat),header = TRUE)
  rownames(cts) <- cts$gene_id

  cts$gene_id <- NULL
  
  # generate phenotype data
  num_samples <- length(list.files(paste0('../',exp_folder,species)))
  pheno_data <- data.frame('Ids'=1:num_samples,'Sex'=1:num_samples)
  pheno_data$Ids <-list.files(paste0('../',exp_folder,species))
  pheno_data$Sex <-substr(pheno_data$Ids,9,9)
  pheno_data$Strain <- substr(pheno_data$Ids,5,8)
  row.names(pheno_data) <- pheno_data$Ids
  # generate DESeq object
  dds <- DESeqDataSetFromMatrix(countData = cts,colData = pheno_data,design = ~ Strain + Sex)
  
  # only keep genes with at least 10 reads across samples
  keep <- rowSums(counts(dds)) >= 10
  dds <- dds[keep,]
  dds <- DESeq(dds)
  res <- results(dds,alpha = signif)
  resOrdered <- res[order(res$pvalue),]
  resOrdered <- as.data.frame(resOrdered)
  resOrdered$gene_id <- rownames(resOrdered)
  resOrdered <- na.omit(resOrdered)
  # rename the log2foldchange column to l2fc
  resOrdered$l2fc <- resOrdered$log2FoldChange
  resOrdered$log2FoldChange <- NULL
  
  sex_biased_genes <- resOrdered[resOrdered$padj<signif,
                                 c("gene_id", "l2fc", "padj")]
  colnames(sex_biased_genes) <- c("gene_id", "l2fc", "qval")
  # Use a sample from the species to get the unique list of genes
  sample <- pheno_data$Ids[2]
  sample_data <- read.delim(paste0('../',exp_folder,species,'/',sample,'/gene_abund.txt'),sep='\t')
  sample_data <- as.data.frame(unique(sample_data[sample_data$Gene.ID ,c('Gene.ID','Reference')]))
  colnames(sample_data) <- c("gene_id","seqnames")
  # sbg_df will be the final dataframe that contains the sex-biased genes and relevant info
  sbg_df <- merge(sample_data, sex_biased_genes, by = "gene_id")
  sbg_df <- add_bias_fromFC(sbg_df, cts, pheno_data)
  # need to add "sex-bias" to all genes for figure 3
  resOrdered <- add_bias_fromFC(resOrdered, cts, pheno_data)
  resOrdered <- merge(sample_data, resOrdered, by = "gene_id")
  resOrdered$sex[resOrdered$padj > signif] <- 'u'
  # add region column (i.e. X or A)
  resOrdered$region <- as.character(resOrdered$seqnames)
  resOrdered$region[grepl('2L', resOrdered$seqnames) |
                      grepl('2R', resOrdered$seqnames) |
                      grepl('3L', resOrdered$seqnames) |
                      grepl('3R', resOrdered$seqnames) | 
                      (resOrdered$seqnames == '4') | 
                      (resOrdered$seqnames == 'Scf_4')] <- 'A'
  resOrdered$region[grepl('X', resOrdered$seqnames)] <- 'X'
  
  #
  write.csv(sample_data[sample_data$gene_id %in% rownames(resOrdered),],
            file = paste0(species,'/genes_with_finite_p_val.txt'),quote = F,row.names = F)
  write.csv(sbg_df, file = paste0(species,'/sex_biased_genes_',species,'.txt'))
  write.csv(resOrdered, file = paste0(species,'/total_DESeq_output.txt'))
}
